//! T-P1 .. T-P3 — the pipeline constraints from `filter/src/pipeline/checks.rs`,
//! asserted against a real [`FilterPipeline`] built from a registry with
//! `llm_d_sc` registered exactly as the Praxis server would register it.

use praxis_core::config::SkipPipelineChecks;
use praxis_filter::{FailureMode, FilterEntry, FilterPipeline, FilterRegistry};

/// A registry with the built-ins plus this crate's exported filters.
///
/// `register_filters` is generated by `export_filters!`, so this is the same
/// entry point the Praxis server's build-time discovery calls.
fn registry() -> FilterRegistry {
    let mut registry = FilterRegistry::with_builtins();
    llm_d_sc_praxis_filter::register_filters(&mut registry);
    registry
}

/// Build a filter entry from a type name and a YAML config body.
fn entry(filter_type: &str, config: &str) -> FilterEntry {
    FilterEntry {
        branch_chains: None,
        conditions: vec![],
        filter_type: filter_type.to_owned(),
        config: serde_yaml::from_str(config).expect("test filter config must be well-formed"),
        name: None,
        response_conditions: vec![],
        failure_mode: FailureMode::default(),
    }
}

/// The `llm_d_sc` entry used across these tests.
fn llm_d_sc_entry() -> FilterEntry {
    entry(
        "llm_d_sc",
        "endpoint: \"127.0.0.1:50051\"\ndefault_cluster: general\n\
         routes:\n  - {label: SIMPLE, cluster: small}\n  - {label: COMPLEX, cluster: large}\n",
    )
}

/// A `load_balancer` entry defining the named clusters.
fn load_balancer_entry(clusters: &[&str]) -> FilterEntry {
    let mut body = String::new();
    for name in clusters {
        use std::fmt::Write as _;
        let _written = writeln!(body, "  - name: {name}\n    endpoints: [\"127.0.0.1:3001\"]");
    }
    entry("load_balancer", &format!("clusters:\n{body}"))
}

/// Build the pipeline and return its structural errors.
fn build_errors(mut entries: Vec<FilterEntry>) -> Vec<String> {
    let registry = registry();
    let pipeline = FilterPipeline::build(&mut entries, &registry).expect("all filters must instantiate");
    pipeline.ordering_errors(&entries, false, &SkipPipelineChecks::default())
}

// -----------------------------------------------------------------------------
// T-P1
// -----------------------------------------------------------------------------

#[test]
fn t_p1_llm_d_sc_then_load_balancer_builds_clean() {
    let errors = build_errors(vec![
        llm_d_sc_entry(),
        load_balancer_entry(&["small", "large", "general"]),
    ]);

    assert!(
        errors.is_empty(),
        "llm_d_sc + load_balancer must validate cleanly, got: {errors:?}"
    );
}

#[test]
fn t_p1_llm_d_sc_satisfies_the_load_balancer_cluster_selector_requirement() {
    // Without a cluster-selecting filter the load balancer has nothing to act
    // on; `selects_cluster() == true` is what makes llm_d_sc a drop-in
    // replacement for `router` in this position.
    let without = build_errors(vec![load_balancer_entry(&["small"])]);
    assert!(
        without.iter().any(|e| e.contains("without a preceding router")),
        "a bare load_balancer should be rejected, got: {without:?}"
    );

    let with = build_errors(vec![
        llm_d_sc_entry(),
        load_balancer_entry(&["small", "large", "general"]),
    ]);
    assert!(with.is_empty(), "llm_d_sc must satisfy the requirement, got: {with:?}");
}

// -----------------------------------------------------------------------------
// T-P2
// -----------------------------------------------------------------------------

#[test]
fn t_p2_llm_d_sc_and_router_before_the_same_load_balancer_is_an_error() {
    // Two cluster-selecting filters compete for ctx.cluster and the later one
    // silently wins, so Praxis rejects the chain. This is why POC configs use
    // `llm_d_sc` *instead of* `router`, not alongside it.
    let errors = build_errors(vec![
        llm_d_sc_entry(),
        entry("router", "routes:\n  - {path_prefix: \"/\", cluster: small}\n"),
        load_balancer_entry(&["small", "large", "general"]),
    ]);

    let conflict = errors
        .iter()
        .find(|e| e.contains("multiple cluster-selecting filters"))
        .unwrap_or_else(|| panic!("expected a conflicting-cluster-selector error, got: {errors:?}"));
    assert!(
        conflict.contains("llm_d_sc") && conflict.contains("router"),
        "the error should name both selectors: {conflict}"
    );
}

#[test]
fn t_p2_router_before_a_different_load_balancer_is_fine() {
    // The check is per load_balancer, so the constraint is "not in the same
    // chain segment", not "never in the same chain".
    let errors = build_errors(vec![
        llm_d_sc_entry(),
        load_balancer_entry(&["small", "large", "general"]),
    ]);
    assert!(errors.is_empty(), "control case must be clean, got: {errors:?}");
}

// -----------------------------------------------------------------------------
// T-P3
// -----------------------------------------------------------------------------

#[test]
fn t_p3_a_route_cluster_missing_from_the_load_balancer_is_an_error() {
    // `large` is mapped by the filter but never defined downstream.
    let errors = build_errors(vec![llm_d_sc_entry(), load_balancer_entry(&["small", "general"])]);

    assert!(
        errors
            .iter()
            .any(|e| e.contains("'large'") && e.contains("not defined in the")),
        "a mapped cluster with no load_balancer definition must be rejected, got: {errors:?}"
    );
}

#[test]
fn t_p3_default_cluster_missing_from_the_load_balancer_is_an_error() {
    // This is why `selected_clusters()` must include `default_cluster`: the
    // fail-open path would otherwise select a cluster the load balancer has
    // never heard of, and only at runtime.
    let errors = build_errors(vec![llm_d_sc_entry(), load_balancer_entry(&["small", "large"])]);

    assert!(
        errors
            .iter()
            .any(|e| e.contains("'general'") && e.contains("not defined in the")),
        "the fail-open cluster must be validated at build time, got: {errors:?}"
    );
}

// -----------------------------------------------------------------------------
// Registration
// -----------------------------------------------------------------------------

#[test]
fn export_filters_registers_llm_d_sc_alongside_the_builtins() {
    let registry = registry();

    assert!(
        registry.available_filters().contains(&"llm_d_sc"),
        "export_filters! must register the filter under its documented name"
    );
    assert!(
        registry.available_filters().contains(&"load_balancer"),
        "registration must not displace the built-ins"
    );
}

#[test]
fn an_invalid_config_fails_at_pipeline_build_not_at_request_time() {
    let mut entries = vec![entry(
        "llm_d_sc",
        "endpoint: \"127.0.0.1:50051\"\ndefault_cluster: general\nroutes: []\n",
    )];
    let Err(error) = FilterPipeline::build(&mut entries, &registry()) else {
        panic!("empty routes must fail the pipeline build");
    };

    assert!(error.to_string().contains("routes must not be empty"), "got: {error}");
}

// -----------------------------------------------------------------------------
// The shipped example
// -----------------------------------------------------------------------------

#[test]
fn the_example_config_parses_and_its_pipeline_validates() {
    // The README tells operators to run this file. A stale example is a
    // support burden, so it is checked the same way the server would check it.
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("examples/llm-d-sc-routing.yaml");
    let yaml = std::fs::read_to_string(&path).expect("the example config must exist");

    let config = praxis_core::config::Config::from_yaml(&yaml)
        .unwrap_or_else(|e| panic!("{} is not a valid Praxis config: {e}", path.display()));

    let chains: std::collections::HashMap<&str, &[FilterEntry]> = config
        .filter_chains
        .iter()
        .map(|chain| (chain.name.as_str(), chain.filters.as_slice()))
        .collect();

    let registry = registry();
    for listener in &config.listeners {
        let mut entries: Vec<FilterEntry> = listener
            .filter_chains
            .iter()
            .flat_map(|name| {
                chains
                    .get(name.as_str())
                    .unwrap_or_else(|| panic!("listener references unknown chain '{name}'"))
                    .iter()
                    .cloned()
            })
            .collect();

        let pipeline = FilterPipeline::build_with_chains(&mut entries, &registry, &chains)
            .unwrap_or_else(|e| panic!("example pipeline must build: {e}"));
        let errors = pipeline.ordering_errors(&entries, false, &SkipPipelineChecks::default());
        assert!(errors.is_empty(), "example pipeline must validate cleanly: {errors:?}");
    }
}
