//! `llm_d_sc` — a Praxis HTTP filter that routes by semantic classification.
//!
//! The filter extracts the prompt from an OpenAI-shaped request body, asks
//! [llm-d-sc] to classify it over the existing `classify.Classify` gRPC
//! contract, and selects a Praxis **cluster** from the returned ranked label.
//! llm-d-sc stays a signal producer; Praxis keeps routing authority.
//!
//! See `SPEC.md` for the full contract. The short version:
//!
//! * the request body is never modified — the filter is read-only on the payload;
//! * the default posture is fail-open (`default_cluster`) on every classifier
//!   failure, because a classifier outage should degrade routing quality, not
//!   take the gateway down;
//! * client-supplied `x-llm-d-sc-*` headers are stripped on every path, so a
//!   caller can never forge provenance.
//!
//! ```yaml
//! - filter: llm_d_sc
//!   endpoint: "127.0.0.1:50051"
//!   default_cluster: general
//!   routes:
//!     - { label: SIMPLE,    cluster: small }
//!     - { label: COMPLEX,   cluster: large }
//! ```
//!
//! [llm-d-sc]: https://github.com/llm-d/llm-d-sc

#![deny(missing_docs)]

pub mod client;
pub mod config;
pub mod filter;
pub mod metrics;
pub mod prompt;

#[cfg(feature = "test-server")]
pub mod testing;

/// Generated `classify.Classify` bindings from the vendored
/// `proto/classify.proto` (byte-identical to llm-d-sc's copy — see T-U6).
///
/// A client only in a normal build; the `test-server` feature additionally
/// generates the server stubs the integration suite needs.
pub mod pb {
    #![allow(
        missing_docs,
        clippy::all,
        clippy::pedantic,
        reason = "generated by tonic-prost-build"
    )]
    tonic::include_proto!("classify");
}

pub use config::{FailureAction, LlmDScConfig, RouteEntry};
pub use filter::{Decision, LlmDScFilter, Provenance, Route};

praxis_filter::export_filters! {
    http "llm_d_sc" => LlmDScFilter::from_config,
}
